"""Increase password_hash length

Revision ID: 4958707d18c2
Revises: 89ec38008251
Create Date: 2025-09-30 14:03:59.106038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4958707d18c2'
down_revision = '89ec38008251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
